import { Router } from 'express';
import adminRoutes from './admin.routes.js';
import checkoutRoutes from './checkout.routes.js';
import contactEnquiryRoutes from './contactEnquiry.routes.js';
import customerAuthRoutes from './customerAuth.routes.js';
import customerPaymentRoutes from './customerPayment.routes.js';
import diningSessionRoutes from './diningSession.routes.js';
import hotelRoutes from './hotel.routes.js';
import legalPageRoutes from './legalPage.routes.js';
import managerRoutes from './manager.routes.js';
import menuRoutes from './menu.routes.js';
import notificationRoutes from './notification.routes.js';
import openOrderRoutes from './openOrder.routes.js';
import orderRoutes from './order.routes.js';
import ownerRoutes from './owner.routes.js';
import subscriptionRoutes from './subscription.routes.js';
import tableRoutes from './tables.routes.js';
import userRoutes from './user.routes.js';
import websiteSettingsRoutes from './websiteSettings.routes.js';

const router = Router();
router.use('/user', userRoutes);
router.use('/hotel', hotelRoutes);
router.use('/manager', managerRoutes);
router.use('/legal-pages', legalPageRoutes);
router.use('/table', tableRoutes);
router.use('/menu', menuRoutes);
router.use('/order', orderRoutes);
router.use('/owner', ownerRoutes);
router.use('/orders', openOrderRoutes);
router.use('/notification', notificationRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/customer-payment', customerPaymentRoutes);
router.use('/customer-auth', customerAuthRoutes);
router.use('/contact-enquiries', contactEnquiryRoutes);
router.use('/rc-session', diningSessionRoutes);
router.use('/admin', adminRoutes);
router.use('/website-settings', websiteSettingsRoutes);

export default router;
